name: Deploy ExpertoContable to WebLogic (from CI ZIP)

on:
  workflow_call:
    inputs:
      zip_artifact_name:
        description: 'Nombre del archivo ZIP presente en el runner (ej. PR-123.zip)'
        required: true
        type: string
      artifact_name:
        description: 'Nombre del archivo EAR/WAR/JAR dentro del ZIP'
        required: true
        type: string
      environment:
        description: 'Entorno de despliegue ("integration", "laboratory" o "production")'
        required: true
        type: string
    secrets:
      AZURE_VM_SSH_USER:
        description: 'Usuario SSH para la VM de Azure'
        required: true
      AZURE_VM_SSH_PRIVATE_KEY:
        description: 'Llave privada SSH para la VM de Azure'
        required: true
      WEBLOGIC_PASSWORD_DESARROLLO:
        description: 'Password para WebLogic en desarrollo'
        required: true
      WEBLOGIC_PASSWORD_LABORATORIO:
        description: 'Password para WebLogic en laboratorio'
        required: true
      WEBLOGIC_PASSWORD_PRODUCCION:
        description: 'Password para WebLogic en producci贸n'
        required: true
      AZURE_VM_IP_DESARROLLO:
        description: 'IP de la VM de desarrollo'
        required: true
      AZURE_VM_IP_LABORATORIO:
        description: 'IP de la VM de laboratorio'
        required: true
      AZURE_VM_IP_PRODUCCION:
        description: 'IP de la VM de producci贸n'
        required: true

jobs:
  deploy_pipeline:
    name: CD - Preparar artefacto presente y desplegar en WebLogic
    runs-on: ubuntu-latest
    env:
      SSH_HOST_VAR: ${{ (inputs.environment == 'integration' && secrets.AZURE_VM_IP_DESARROLLO) || (inputs.environment == 'laboratory' && secrets.AZURE_VM_IP_LABORATORIO) || secrets.AZURE_VM_IP_PRODUCCION }}
      SSH_USER_VAR: ${{ secrets.AZURE_VM_SSH_USER }}
      WEBLOGIC_PASSWORD: ${{ (inputs.environment == 'integration' && secrets.WEBLOGIC_PASSWORD_DESARROLLO) || (inputs.environment == 'laboratory' && secrets.WEBLOGIC_PASSWORD_LABORATORIO) || secrets.WEBLOGIC_PASSWORD_PRODUCCION }}
      WEBLOGIC_ADMIN_URL: ${{ (inputs.environment == 'integration' && 't3://10.229.165.5:7001') || (inputs.environment == 'laboratory' && 't3://TU_LAB_HOST:7001') || 't3://TU_PROD_HOST:7001' }}
      WEBLOGIC_TARGETS: ${{ (inputs.environment == 'integration' && 'CLUSTER_HWEC-D') || (inputs.environment == 'laboratory' && 'CLUSTER_HWEC-L') || 'CLUSTER_HWEC-P' }}
      WEBLOGIC_USERNAME: 'weblogicdeploy'
      WEBLOGIC_HOME_LIB_PATH: '/u01/WLS14.1.1/middleware/wlserver/server/lib/'
      ARTIFACT_DEST_DIR: '/u01/WLS14.1.1/middleware/domains/instaladores'
    steps:

      - name: " [Paso 1] Definir nombres de artefacto y aplicaci贸n para WebLogic"
        id: setvars
        run: |
          echo "artifact_filename=${{ inputs.artifact_name }}" >> $GITHUB_ENV
          APP_NAME="${{ inputs.artifact_name }}"
          echo "application_name=$APP_NAME" >> $GITHUB_ENV

      - name: " [Paso 2] Extraer artefacto del ZIP local"
        run: |
          unzip -o "${{ inputs.zip_artifact_name }}" "${{ inputs.artifact_name }}"
          ls -l "${{ inputs.artifact_name }}"

      - name: " [Paso 3] Copiar artefacto al servidor WebLogic (Azure VM)"
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ env.SSH_HOST_VAR }}
          username: ${{ env.SSH_USER_VAR }}
          key: ${{ secrets.AZURE_VM_SSH_PRIVATE_KEY }}
          source: "${{ inputs.artifact_name }}"
          target: "${{ env.ARTIFACT_DEST_DIR }}/"

      - name: "Ч [Paso 4] Desinstalar versi贸n anterior del aplicativo en WebLogic (Undeploy, ignora error si no existe)"
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ env.SSH_HOST_VAR }}
          username: ${{ env.SSH_USER_VAR }}
          key: ${{ secrets.AZURE_VM_SSH_PRIVATE_KEY }}
          script: |
            echo "Intentando undeploy de ${{ env.application_name }}"
            java -cp ${{ env.WEBLOGIC_HOME_LIB_PATH }}/weblogic.jar weblogic.Deployer \
              -adminurl ${{ env.WEBLOGIC_ADMIN_URL }} \
              -username ${{ env.WEBLOGIC_USERNAME }} \
              -password ${{ env.WEBLOGIC_PASSWORD }} \
              -undeploy \
              -name ${{ env.application_name }} \
              -targets ${{ env.WEBLOGIC_TARGETS }} || echo "Undeploy fall贸, probablemente la app no existe. Continuando..."

      - name: " [Paso 5] Desplegar nuevo artefacto en WebLogic"
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ env.SSH_HOST_VAR }}
          username: ${{ env.SSH_USER_VAR }}
          key: ${{ secrets.AZURE_VM_SSH_PRIVATE_KEY }}
          script: |
            echo "Realizando deploy de ${{ env.application_name }}"
            java -cp ${{ env.WEBLOGIC_HOME_LIB_PATH }}/weblogic.jar weblogic.Deployer \
              -adminurl ${{ env.WEBLOGIC_ADMIN_URL }} \
              -username ${{ env.WEBLOGIC_USERNAME }} \
              -password ${{ env.WEBLOGIC_PASSWORD }} \
              -deploy \
              -name ${{ env.application_name }} \
              -source ${{ env.ARTIFACT_DEST_DIR }}/${{ env.artifact_filename }} \
              -targets ${{ env.WEBLOGIC_TARGETS }} \
              -upload

      # - name: " [Paso 6] (Opcional) Reiniciar manejadores y limpiar cache"
      #   uses: appleboy/ssh-action@v0.1.7
      #   with:
      #     host: ${{ env.SSH_HOST_VAR }}
      #     username: ${{ env.SSH_USER_VAR }}
      #     key: ${{ secrets.AZURE_VM_SSH_PRIVATE_KEY }}
      #     script: |
      #       # Aqu铆 comandos para reiniciar servicios y limpiar cache
